services:
  postgres:
    image: postgres:15-alpine
    container_name: llm_poc_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: llm_poc_django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d llm_poc_django"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
