"""update counter table

Revision ID: 4b9061d5a2d7
Revises: d7af48742a25
Create Date: 2025-09-10 14:40:09.220197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9061d5a2d7'
down_revision = 'd7af48742a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_user_counter'), type_='unique')
        batch_op.create_unique_constraint('uq_user_date_counter', ['user_id', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counters', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_date_counter', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_counter'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
