"""Add Counter table

Revision ID: d7af48742a25
Revises: 7fd7ee66de69
Create Date: 2025-09-10 14:27:26.736931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7af48742a25'
down_revision = '7fd7ee66de69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_counter')
    )
    with op.batch_alter_table('counters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counters_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counters_user_id'))

    op.drop_table('counters')
    # ### end Alembic commands ###
